# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
    exclude: ^tests/snapshots
  - id: end-of-file-fixer
  - id: check-toml
  - id: check-yaml
  - id: check-json
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: debug-statements
  - id: check-executables-have-shebangs
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.800
  hooks:
  - id: mypy
- repo: https://github.com/pycqa/isort
  rev: 5.6.3
  hooks:
    - id: isort
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    name: Blacken Python files
- repo: https://github.com/asottile/blacken-docs
  rev: v1.9.1
  hooks:
  - id: blacken-docs
    name: Blacken Python code blocks in documentation files
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8
    name: Lint Python files
    exclude: (^tests/snapshots|^alembic/versions)
- repo: local
  hooks:
    - id: deps-api-pip
      name: Check API's requirements.txt & pyproject.toml are synced
      language: system
      entry: make deps-api-pip
      pass_filenames: false
- repo: local
  hooks:
  - id: tests
    name: Run tests
    entry: make tests
    language: system
    stages:
    - merge-commit
    - push
