language: python
python:
  - "3.7"
branches:
  # avoid duplicate jobs on updated PRs
  only:
    - master
cache:
  pip: true
  directories:
    - "$HOME/.cache/"
    - "$HOME/virtualenv/"
    - node_modules
before_install:
  - make init-stockfish-linux
  - export PATH="`pwd`/bin:${PATH}"
  - export CHESS_BLUNDERS_ENGINE="stockfish"
  - which stockfish || (echo $PATH && false)
  - nvm install 15
  - npm config set cache "$HOME/.cache/npm"
install:
  - make init
  - poetry env info
  - poetry env list
  - poetry config --list
script:
  - make ci-integration
after_success:
  - bash <(curl -s https://codecov.io/bash) -y .ci/codecov.yml
deploy:
  provider: script
  script: make deploy-api-prod
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false"
