language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
branches:
  # avoid duplicate jobs on updated PRs
  only:
    - master
cache:
  pip: true
  directories:
    - "$HOME/.cache/"
    - "$HOME/virtualenv/"
    - node_modules
before_install:
  - make init-stockfish-linux
  - mkdir chess_blunders/app/api/bin
  - cp bin/stockfish chess_blunders/app/api/bin
  - export PATH="`pwd`/chess_blunders/app/api/bin:${PATH}"
  - export CHESS_BLUNDERS_ENGINE="stockfish"
  - which stockfish || (echo $PATH && false)
  - nvm install 15
  - npm config set cache "$HOME/.cache/npm"
install:
  - make init
script:
  - make ci-integration
after_success:
  - bash <(curl -s https://codecov.io/bash) -y .ci/codecov.yml
deploy:
  provider: script
  script: make deploy-api-prod
  skip_cleanup: true
  on:
    branch: master
    python: "3.8"
    condition: $TRAVIS_PULL_REQUEST = "false"
