language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
branches:
  # avoid duplicate jobs on updated PRs
  only:
    - master
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"
    - "$HOME/.cache/pypoetry"
    - .venv
before_install:
  - make init-stockfish-linux
  - export PATH="`pwd`/bin:${PATH}"
  - export CHESS_BLUNDERS_ENGINE="stockfish"
  - which stockfish || (echo $PATH && false)
install:
  - make init
script:
  make ci-integration
after_success:
  - bash <(curl -s https://codecov.io/bash) -y .ci/codecov.yml
  - >
    test $TRAVIS_BRANCH = "master" &&
    test $TRAVIS_PULL_REQUEST = "false" &&
    make ci-deployment
