# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="chess-blunders",
    version="0.1.0",
    description="Review the mistakes from your own games.",
    python_requires="==3.*,>=3.7.0",
    author="Ludovic Tiako",
    author_email="ludovic.tiako@gmail.com",
    license="MIT",
    packages=["chess_blunders"],
    package_dir={"": "."},
    package_data={},
    install_requires=[],
    extras_require={
        "dev": [
            "black==20.*,>=20.8.0.b1",
            "dephell==0.*,>=0.8.3",
            "pre-commit==2.*,>=2.9.3",
            "pytest==6.*,>=6.2.2",
            "pytest-cov==2.*,>=2.11.1",
        ]
    },
)
