env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
rules: {}
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .ts
        - .jsx
        - .tsx
