frameworkVersion: "2"

app: chess-blunders
service: chess-blunders-api

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  environment:
    CHESS_BLUNDERS_ENGINE: bin/stockfish
  iam:
    role:
      statements:
        - Effect: Allow
          Action: "sns:Publish"
          Resource:
            Ref: BlundersJobsTopic

functions:
  blunders_worker:
    handler: handlers.blunders_worker
    timeout: 900
    # memorySize: 3072
    events:
      - sns:
          arn:
            Ref: BlundersJobsTopic
          topicName: blunders-jobs-topic

  get_games_chessdotcom:
    handler: handlers.get_games_chessdotcom
    events:
      - httpApi:
          method: GET
          path: /games/chessdotcom/{username}

  post_blunders:
    handler: handlers.post_blunders
    environment:
      JOBS_TOPIC_ARN:
        Ref: BlundersJobsTopic
    events:
      - httpApi:
          method: POST
          path: /blunders

package:
  include:
    - bin/*
  exclude:
    - node_modules/**

custom:
  stage: ${opt:stage, self.provider.stage, "dev"}
  pythonRequirements:
    slim: true
    pythonBin: python
    invalidateCaches: true
    useStaticCache: false
    staticCacheMaxVersions: 10

resources:
  Description: "CloudFormation template for Chess-Blunders' API service."

  Resources:
    BlundersJobsTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: "${self:custom.stage}-blunders-jobs-topic"
        DisplayName: "Blunders jobs to be processed."

plugins:
  - serverless-python-requirements
